### ISSUE TITLE
Define goals and milestones

### ISSUE THREAD

**Issue by piranhaplant97** [uol-mediaprocessing/group-projects-sudoku-solver#1]
- [x] Describe tasks from the lecture and add them in main_sudoku.ipynb
- [x] Divide goal into tasks
- [x] Split tasks into milestones

<img width="525" alt="1" src="https://user-images.githubusercontent.com/49309188/67088376-4b7ea680-f1a5-11e9-952b-93f5235d8071.png">
<img width="547" alt="2" src="https://user-images.githubusercontent.com/49309188/67088378-4b7ea680-f1a5-11e9-9a2e-1c36c4a89fe3.png">
